# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            python -m venv ~/test-venv
            . ~/test-venv/bin/activate
            pip install --upgrade botocore
            pip install --upgrade requests==2.18.4
            pip install --upgrade -r requirements.txt
            deactivate

      - run:
          name: run tests
          command: |
            . ~/test-venv/bin/activate
            python -B -m pytest -v
            deactivate

      - run:
          name: deploy
          command: |
            ./deploy.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master